// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       number[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:            string;
  type:          string;
  place_type:    string[];
  relevance:     number;
  properties:    Properties;
  text_es:       string;
  place_name_es: string;
  text:          string;
  place_name:    string;
  bbox:          number[];
  center:        number[];
  context:       Context[];
}

export interface Context {
  id:          string;
  wikidata:    string;
  mapbox_id:   string;
  text_es:     string;
  language_es: string;
  text:        string;
  language:    string;
  short_code?: string;
}

export interface Properties {
  mapbox_id: string;
}
